# 端口号
server:
  port: 8888

#数据库连接信息
spring:
  profiles:
    active: local

#mybatos-Plus配置
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml

#flowable配置
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  database-schema-update: true
